# Config module of parameter set 8


class Config():

    POST_NUM_INFERENCE_IT = 25
    
    POST_SDIMS_GAUSSIAN_X = 0.005
    POST_SDIMS_GAUSSIAN_Y = 0.005
    POST_COMPAT_GAUSSIAN = 15
    
    POST_SDIMS_BILATERAL_X = 20
    POST_SDIMS_BILATERAL_Y = 20
    POST_SCHAN_BILATERAL_R = 100
    POST_SCHAN_BILATERAL_G = 100
    POST_SCHAN_BILATERAL_B = 100
    POST_COMPAT_BILATERAL = 8
