# Config module of parameter set 1

class Config():
        

    POST_NUM_INFERENCE_IT = 25
    
    POST_SDIMS_GAUSSIAN_X = 0.05
    POST_SDIMS_GAUSSIAN_Y = 0.05
    POST_COMPAT_GAUSSIAN = 15
    
    POST_SDIMS_BILATERAL_X = 120
    POST_SDIMS_BILATERAL_Y = 120
    POST_SCHAN_BILATERAL_R = 40
    POST_SCHAN_BILATERAL_G = 40
    POST_SCHAN_BILATERAL_B = 40
    POST_COMPAT_BILATERAL = 8
